# Every field in a theme file is optional.

shadow = false
borders = "outset" # Alternatives are "none" and "simple"

[colors]
	# If the value is an array, the first valid
	# and supported color will be used.
	background = ["#282A36", "black"]

	shadow     = ["#222288", "blue"]
	view       = ["#44475A"]

	primary   = ["#F8F8F2", "white"]
	secondary = "#6272A4"
	tertiary  = "#BD93F9"

	title_primary   = ["#BD93F9", "purple"]
	title_secondary = "#6272A4"

	# Lower precision values can use only 3 digits.
	highlight          = "#6272A4"
	highlight_inactive = "#44475A"

[styles.highlight]
    effects = []
    front = ["#BD93F9", "purple"]
    back = "inherit_parent"